### ISSUE TITLE
Enhance stack traces/debugging for CE's exposed in this project

### ISSUE THREAD

**Issue by baronfel** [demystifyfp/FsToolkit.ErrorHandling#76]
I know that we don't typically throw exceptions when using results and such, but I think it would be a good idea to put the tips from https://github.com/dotnet/fsharp/pull/4867 into place for the CEs in this repository. Mostly this comes down to 

* have CE's just call matching module-level functions where applicable, and
* `inline` as many CE members as is practical, and
* if try/with is used anywhere and there are guard clauses, be sure to have a catch-all branch that correctly throws the original exception.

**Comment by TheAngryByrd** [comment]
I will look into this after I get the applicative work done.

**Comment by TheAngryByrd** [comment]
Chet and I did a livestream of this: https://www.twitch.tv/videos/625998302 

Here are some of the initial results:

---

The result CE's original stack trace.

```
System.Exception: I'm a failure
   at ResultCETests.failureFunc[a]() in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 282
   at ResultCETests.iDoCalls@288-2.Invoke(Int32 _arg2) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 288
   at FsToolkit.ErrorHandling.ResultCE.ResultBuilder.Bind[T,TError,U](FSharpResult`2 result, FSharpFunc`2 binder) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/ResultCE.fs:line 21
   at ResultCETests.iDoCalls@287-1.Invoke(Int32 _arg1) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 287
   at FsToolkit.ErrorHandling.ResultCE.ResultBuilder.Bind[T,TError,U](FSharpResult`2 result, FSharpFunc`2 binder) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/ResultCE.fs:line 21
   at ResultCETests.iDoCalls@286.Invoke(Unit unitVar) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 286
   at FsToolkit.ErrorHandling.ResultCE.ResultBuilder.Run[T,TError](FSharpFunc`2 generator) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/ResultCE.fs:line 31
   at ResultCETests.iDoCalls[a]() in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 285
   at ResultCETests.ResultCE stack traces@294.Invoke(Unit unitVar0) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 295
   at Expecto.Impl.execTestAsync@566-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at <StartupCode$FSharp-Core>.$Async.StartChild@1666-5.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1666
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
```

As you can see we're spending a lot of time in the CE builder itself.  With some inlining we've gotten to this stack trace:

```
System.Exception: I'm a failure
   at ResultCETests.failureFunc[a]() in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 282
   at ResultCETests.iDoCalls@288-2.Invoke(Int32 _arg2) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 288
   at ResultCETests.iDoCalls@287-1.Invoke(Int32 _arg1) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 287
   at ResultCETests.iDoCalls@286.Invoke(Unit unitVar) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 286
   at ResultCETests.iDoCalls[a]() in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 285
   at ResultCETests.ResultCE stack traces@294.Invoke(Unit unitVar0) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/ResultCE.fs:line 295
   at Expecto.Impl.execTestAsync@566-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
```

Which shows a vast improvement to clarify of where the error is coming from and removing the needless stackframes.

---

AsyncResult original stacktrace:

```
System.Exception: I'm a failure
   at AsyncResultCETests.failureFunc@422.Invoke(Unit unitVar) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 422
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at FsToolkit.ErrorHandling.Async.bind@8-1.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/Async.fs:line 8
   at FsToolkit.ErrorHandling.Async.bind@8-1.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/Async.fs:line 8
   at FsToolkit.ErrorHandling.AsyncResultCE.ReturnFrom@29.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/AsyncResultCE.fs:line 29
   at FsToolkit.ErrorHandling.AsyncResultCE.Bind@46-3.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/AsyncResultCE.fs:line 46
   at FsToolkit.ErrorHandling.AsyncResultCE.ReturnFrom@29.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/AsyncResultCE.fs:line 29
   at FsToolkit.ErrorHandling.AsyncResultCE.Bind@46-3.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/AsyncResultCE.fs:line 46
   at AsyncResultCETests.AsyncResultCE stack traces@435-2.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 435
   at <StartupCode$FSharp-Core>.$Async.StartChild@1666-5.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1666
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109

```

AsyncResult improved stacktrace:

```
System.Exception: I'm a failure
   at AsyncResultCETests.failureFunc@422.Invoke(Unit unitVar) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 422
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at AsyncResultCETests.iDoCalls@428-8.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 428
   at AsyncResultCETests.iDoCalls@428-13.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 428
   at AsyncResultCETests.iDoCalls@427-14.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 427
   at AsyncResultCETests.iDoCalls@427-18.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 427
   at AsyncResultCETests.iDoCalls@426-19.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 426
   at AsyncResultCETests.iDoCalls@426-23.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 426
   at AsyncResultCETests.AsyncResultCE stack traces@435-2.Invoke(AsyncActivation`1 ctxt) in /Users/jimmybyrd/Documents/GitHub/FsToolkit.ErrorHandling/tests/FsToolkit.ErrorHandling.Tests/AsyncResultCE.fs:line 435
   at <StartupCode$FSharp-Core>.$Async.StartChild@1666-5.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1666
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
````

There's not a lot of gains in this scenario but it does make the error more clear in the sense we're not spending time in the CE builder, but it doesn't reduce the stackframes. 


---


Given this I'm going to go ahead and inline all Bind/ReturnFrom/BindReturn/MergeSources methods and possibly any module level functions like `AsyncResult.bind`
